name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  clock: ^1.1.2
  figma_squircle: ^0.6.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^3.0.3
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  hooks_riverpod: ^3.0.3
  image_picker: ^1.2.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  meta: ^1.16.0
  package_info_plus: ^9.0.0
  riverpod: ^3.0.3
  shared_preferences: ^2.5.3
  simple_logger: ^1.10.0
  url_launcher: ^6.3.2
  custom_refresh_indicator: ^4.0.1
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_storage: ^13.0.4
  cloud_firestore: ^6.1.0
  async: ^2.13.0
  image_editor_plus: ^1.0.8
  flutter_image_compress: ^2.4.0
  hashlib: ^2.2.0
  crop_your_image: ^2.0.0
  extended_image: ^10.0.1
  image: ^4.5.4
  path: ^1.9.1
  firebase_messaging: ^16.0.4
  camera: ^0.11.3
  share_plus: ^12.0.1
  cloud_functions: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.8.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  build_runner: ^2.10.4
  riverpod_lint: ^3.0.3
  flutter_launcher_icons: ^0.14.4
  rename_app: ^1.6.5

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Noto_Sans_JP/
    - assets/fonts/Noto_Sans_JP/static/
    - assets/app_icons/
  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Medium.ttf
          weight: 500
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Bold.ttf
          weight: 700
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Black.ttf
          weight: 900