# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Cache pub dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-
            
      - name: Install dependencies
        run: fvm dart pub get

      - name: Check code formatting
        id: format-check
        run: |
          if fvm dart format --output=none --set-exit-if-changed .; then
            echo "✅ No files that required formatting." >> $GITHUB_STEP_SUMMARY
            echo "formatting_failed=false" >> $GITHUB_OUTPUT
          else
            echo "❌ Formatting is required." >> $GITHUB_STEP_SUMMARY
            echo "formatting_failed=true" >> $GITHUB_OUTPUT
          fi

      - name: Comment on PR if format failed
        if: steps.format-check.outputs.formatting_failed == 'true' && failure()
        uses: actions/github-script@v7
        with:
          script: |
            const comment = '## format failed\n\n' +
                          'フォーマットを実行してください：\n\n' +
                          '```bash\n' +
                          'fvm dart format .\n' +
                          '```';

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });
            
      - name: Analyze project source
        id: analyze-check
        run: fvm dart analyze

      - name: Comment on PR if analysis failed
        if: steps.analyze-check.outputs.formatting_failed == 'true' && failure()
        uses: actions/github-script@v7
        with:
          script: |
            const comment = '## analyze failed\n\n' +
                          '警告を解消してください：\n\n' +
                          '```bash\n' +
                          'fvm dart analyze .\n' +
                          '```';

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });
